version: "3"

services:
  infosistema-banco:
    image: postgres:9.6
    restart: always
    container_name: infosistema-banco
    environment:
      - POSTGRES_PASSWORD=fg2020
      - POSTGRES_MULTIPLE_DATABASES="info","info-test"
    ports:
      - 5435:5432
    volumes:
      - ./config/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/

  infosistema-backend:
    build:
      context: ./backend
    restart: always
    container_name: infosistema-backend
    ports:
      - 3333:3333
    depends_on:
      - infosistema-banco
    links:
      - infosistema-banco

  fontend:
    build:
      context: ./frontend
    restart: always
    container_name: infosistema-frontend
    ports:
      - 80:80
    depends_on:
      - infosistema-backend
      - infosistema-banco
    links:
      - infosistema-backend
